In [1]:
import pandas as pd

In [2]:
import numpy as np


In [4]:
df = pd.read_excel('Adidas US Sales Datasets.xlsx')
df

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
1     Foot Locker   2020-01-02  Northeast       New York    New York   
2     Foot Locker   2020-01-03  Northeast       New York    New York   
3     Foot Locker   2020-01-04  Northeast       New York    New York   
4     Foot Locker   2020-01-05  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9643  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9644  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9645  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9646  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9647  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000     In-store  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
...                         ...             ...         ...          ...  
9643              Men's Apparel            50.0          64       Outlet  
9644            Women's Apparel            41.0         105       Outlet  
9645      Men's Street Footwear            41.0         184       Outlet  
9646    Men's Athletic Footwear            42.0          70       Outlet  
9647    Women's Street Footwear            29.0          83       Outlet  

[9648 rows x 9 columns]

Ques1. Display all rows where Region is "Northeast"

In [8]:
sdf = df.loc[df['Region'] == 'Northeast']
sdf

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
1     Foot Locker   2020-01-02  Northeast       New York    New York   
2     Foot Locker   2020-01-03  Northeast       New York    New York   
3     Foot Locker   2020-01-04  Northeast       New York    New York   
4     Foot Locker   2020-01-05  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9643  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9644  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9645  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9646  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9647  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000     In-store  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
...                         ...             ...         ...          ...  
9643              Men's Apparel            50.0          64       Outlet  
9644            Women's Apparel            41.0         105       Outlet  
9645      Men's Street Footwear            41.0         184       Outlet  
9646    Men's Athletic Footwear            42.0          70       Outlet  
9647    Women's Street Footwear            29.0          83       Outlet  

[2376 rows x 9 columns]

Filter rows where Units Sold is greater than 1000.

In [12]:
mdf = df.loc[df['Units Sold'] >1000 ]
mdf

Retailer Invoice Date     Region           State           City  \
0       Foot Locker   2020-01-01  Northeast        New York       New York   
6       Foot Locker   2020-01-07  Northeast        New York       New York   
12      Foot Locker   2020-01-25  Northeast        New York       New York   
18      Foot Locker   2020-01-31  Northeast        New York       New York   
24      Foot Locker   2020-02-06  Northeast        New York       New York   
30      Foot Locker   2020-03-04  Northeast        New York       New York   
35      Foot Locker   2020-03-09  Northeast        New York       New York   
36      Foot Locker   2020-03-10  Northeast        New York       New York   
37      Foot Locker   2020-03-11  Northeast        New York       New York   
41      Foot Locker   2020-03-15  Northeast        New York       New York   
42      Foot Locker   2020-03-16  Northeast        New York       New York   
43      Foot Locker   2020-03-17  Northeast        New York       New York   
47          Walmart   2020-04-18  Northeast        New York       New York   
48          Walmart   2020-04-19  Northeast        New York       New York   
56          Walmart   2020-04-27  Northeast        New York       New York   
62          Walmart   2020-05-03  Northeast        New York       New York   
106         Walmart   2020-08-26      South           Texas        Houston   
112         Walmart   2020-09-01      South           Texas        Houston   
176       West Gear   2021-01-12       West      California  San Francisco   
716     Foot Locker   2020-08-06       West      Washington        Seattle   
722     Foot Locker   2020-08-12  Southeast         Florida          Miami   
728     Foot Locker   2020-08-18  Southeast         Florida          Miami   
734     Foot Locker   2020-04-24  Southeast         Florida          Miami   
740       West Gear   2020-04-24  Southeast         Florida          Miami   
746       West Gear   2020-04-24  Southeast         Florida          Miami   
752       West Gear   2020-09-11  Southeast         Florida          Miami   
758       West Gear   2020-09-17  Southeast         Florida          Miami   
764     Foot Locker   2020-09-23  Southeast         Florida          Miami   
782   Sports Direct   2020-05-24  Southeast         Florida          Miami   
2295    Foot Locker   2021-01-09  Southeast         Georgia        Atlanta   
2301    Foot Locker   2021-02-07  Southeast         Georgia        Atlanta   
2307    Foot Locker   2021-03-05  Southeast  South Carolina     Charleston   
2319    Foot Locker   2021-05-05  Southeast  South Carolina     Charleston   
2325    Foot Locker   2021-06-07  Southeast  South Carolina     Charleston   
2331    Foot Locker   2021-07-05  Southeast  South Carolina     Charleston   
2337    Foot Locker   2021-08-06  Southeast  South Carolina     Charleston   
2343    Foot Locker   2021-09-05  Southeast  South Carolina     Charleston   
2361    Foot Locker   2021-12-05  Southeast  South Carolina     Charleston   
2403  Sports Direct   2021-07-02  Southeast  North Carolina      Charlotte   
2409  Sports Direct   2021-08-03  Southeast  North Carolina      Charlotte   

                      Product  Price per Unit  Units Sold Sales Method  
0       Men's Street Footwear            50.0        1200     In-store  
6       Men's Street Footwear            50.0        1250     In-store  
12      Men's Street Footwear            50.0        1220       Outlet  
18      Men's Street Footwear            50.0        1200       Outlet  
24      Men's Street Footwear            60.0        1220       Outlet  
30      Men's Street Footwear            60.0        1250       Outlet  
35            Women's Apparel            65.0        1050       Outlet  
36      Men's Street Footwear            60.0        1275       Outlet  
37    Men's Athletic Footwear            55.0        1025       Outlet  
41            Women's Apparel            65.0        1100       Outlet  
42      M

Show records where Price per Unit is equal to $50.00.

In [20]:
df.loc[df['Price per Unit']==50.00]


Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
1     Foot Locker   2020-01-02  Northeast       New York    New York   
5     Foot Locker   2020-01-06  Northeast       New York    New York   
6     Foot Locker   2020-01-07  Northeast       New York    New York   
7     Foot Locker   2020-01-08  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9559       Amazon   2021-11-11  Northeast        Vermont  Burlington   
9602       Amazon   2021-06-19  Northeast  New Hampshire  Manchester   
9625  Foot Locker   2021-10-19  Northeast  New Hampshire  Manchester   
9637  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9643  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   

                      Product  Price per Unit  Units Sold Sales Method  
0       Men's Street Footwear            50.0        1200     In-store  
1     Men's Athletic Footwear            50.0        1000     In-store  
5             Women's Apparel            50.0        1000     In-store  
6       Men's Street Footwear            50.0        1250     In-store  
7     Men's Athletic Footwear            50.0         900       Outlet  
...                       ...             ...         ...          ...  
9559            Men's Apparel            50.0          91       Outlet  
9602          Women's Apparel            50.0         162       Outlet  
9625            Men's Apparel            50.0          58       Outlet  
9637            Men's Apparel            50.0         123       Outlet  
9643            Men's Apparel            50.0          64       Outlet  

[557 rows x 9 columns]

Get all rows where Sales Method is "In-store".


In [23]:
df.loc[df['Sales Method'] == 'In-store']

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
1     Foot Locker   2020-01-02  Northeast       New York    New York   
2     Foot Locker   2020-01-03  Northeast       New York    New York   
3     Foot Locker   2020-01-04  Northeast       New York    New York   
4     Foot Locker   2020-01-05  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
3839       Amazon   2021-06-19  Northeast  New Hampshire  Manchester   
3840       Amazon   2021-06-19  Northeast  New Hampshire  Manchester   
3841       Amazon   2021-06-19  Northeast  New Hampshire  Manchester   
3842       Amazon   2021-06-19  Northeast  New Hampshire  Manchester   
3843       Amazon   2021-07-17  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000     In-store  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
...                         ...             ...         ...          ...  
3839    Women's Street Footwear            55.0         350     In-store  
3840  Women's Athletic Footwear            55.0         325     In-store  
3841              Men's Apparel            65.0         325     In-store  
3842            Women's Apparel            70.0         475     In-store  
3843      Men's Street Footwear            65.0         700     In-store  

[1740 rows x 9 columns]

Select records where Retailer is "Foot Locker" and City is "New York".


In [28]:
df.loc[(df['Retailer'] == 'Foot Locker') & (df['City'] == 'New York')]

Retailer Invoice Date     Region     State      City  \
0     Foot Locker   2020-01-01  Northeast  New York  New York   
1     Foot Locker   2020-01-02  Northeast  New York  New York   
2     Foot Locker   2020-01-03  Northeast  New York  New York   
3     Foot Locker   2020-01-04  Northeast  New York  New York   
4     Foot Locker   2020-01-05  Northeast  New York  New York   
...           ...          ...        ...       ...       ...   
7817  Foot Locker   2020-03-15  Northeast  New York  New York   
7818  Foot Locker   2020-03-16  Northeast  New York  New York   
7819  Foot Locker   2020-03-17  Northeast  New York  New York   
7820  Foot Locker   2020-03-18  Northeast  New York  New York   
7821  Foot Locker   2020-03-31  Northeast  New York  New York   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000     In-store  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
...                         ...             ...         ...          ...  
7817            Women's Apparel            47.0         352       Outlet  
7818      Men's Street Footwear            41.0         375       Outlet  
7819    Men's Athletic Footwear            37.0         359       Outlet  
7820    Women's Street Footwear            37.0         314       Outlet  
7821  Women's Athletic Footwear            40.0         324       Outlet  

[138 rows x 9 columns]

Filter rows where Units Sold is not equal to 1000.


In [29]:
df.loc[df['Units Sold'] != 1000]

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
3     Foot Locker   2020-01-04  Northeast       New York    New York   
4     Foot Locker   2020-01-05  Northeast       New York    New York   
6     Foot Locker   2020-01-07  Northeast       New York    New York   
7     Foot Locker   2020-01-08  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9643  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9644  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9645  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9646  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9647  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
6         Men's Street Footwear            50.0        1250     In-store  
7       Men's Athletic Footwear            50.0         900       Outlet  
...                         ...             ...         ...          ...  
9643              Men's Apparel            50.0          64       Outlet  
9644            Women's Apparel            41.0         105       Outlet  
9645      Men's Street Footwear            41.0         184       Outlet  
9646    Men's Athletic Footwear            42.0          70       Outlet  
9647    Women's Street Footwear            29.0          83       Outlet  

[9635 rows x 9 columns]

Show records where Units Sold is greater than or equal to 900.

In [30]:
df.loc[df['Units Sold'] >= 900]

Retailer Invoice Date     Region           State       City  \
0       Foot Locker   2020-01-01  Northeast        New York   New York   
1       Foot Locker   2020-01-02  Northeast        New York   New York   
2       Foot Locker   2020-01-03  Northeast        New York   New York   
4       Foot Locker   2020-01-05  Northeast        New York   New York   
5       Foot Locker   2020-01-06  Northeast        New York   New York   
...             ...          ...        ...             ...        ...   
2403  Sports Direct   2021-07-02  Southeast  North Carolina  Charlotte   
2409  Sports Direct   2021-08-03  Southeast  North Carolina  Charlotte   
2415  Sports Direct   2021-09-02  Southeast  North Carolina  Charlotte   
2433  Sports Direct   2021-12-02  Southeast  North Carolina  Charlotte   
2475         Amazon   2021-07-09    Midwest            Ohio   Columbus   

                      Product  Price per Unit  Units Sold Sales Method  
0       Men's Street Footwear            50.0        1200     In-store  
1     Men's Athletic Footwear            50.0        1000     In-store  
2     Women's Street Footwear            40.0        1000     In-store  
4               Men's Apparel            60.0         900     In-store  
5             Women's Apparel            50.0        1000     In-store  
...                       ...             ...         ...          ...  
2403    Men's Street Footwear            65.0        1050       Online  
2409    Men's Street Footwear            65.0        1025       Online  
2415    Men's Street Footwear            55.0         925       Online  
2433    Men's Street Footwear            70.0         975       Online  
2475    Men's Street Footwear            65.0         900       Online  

[154 rows x 9 columns]

Filter rows where Price per Unit is less than $50.00

In [31]:
df.loc[df['Price per Unit']<50.00]

Retailer Invoice Date     Region          State        City  \
2     Foot Locker   2020-01-03  Northeast       New York    New York   
3     Foot Locker   2020-01-04  Northeast       New York    New York   
8     Foot Locker   2020-01-21  Northeast       New York    New York   
9     Foot Locker   2020-01-22  Northeast       New York    New York   
14    Foot Locker   2020-01-27  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9642  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9644  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9645  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9646  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9647  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
8       Women's Street Footwear            40.0         950       Outlet  
9     Women's Athletic Footwear            45.0         825       Outlet  
14      Women's Street Footwear            40.0         950       Outlet  
...                         ...             ...         ...          ...  
9642  Women's Athletic Footwear            33.0          51       Outlet  
9644            Women's Apparel            41.0         105       Outlet  
9645      Men's Street Footwear            41.0         184       Outlet  
9646    Men's Athletic Footwear            42.0          70       Outlet  
9647    Women's Street Footwear            29.0          83       Outlet  

[5935 rows x 9 columns]

Display all rows where Units Sold is between 900 and 1200.

In [32]:
df.loc[df['Units Sold'].between(900,1200)]

Retailer Invoice Date     Region           State       City  \
0       Foot Locker   2020-01-01  Northeast        New York   New York   
1       Foot Locker   2020-01-02  Northeast        New York   New York   
2       Foot Locker   2020-01-03  Northeast        New York   New York   
4       Foot Locker   2020-01-05  Northeast        New York   New York   
5       Foot Locker   2020-01-06  Northeast        New York   New York   
...             ...          ...        ...             ...        ...   
2403  Sports Direct   2021-07-02  Southeast  North Carolina  Charlotte   
2409  Sports Direct   2021-08-03  Southeast  North Carolina  Charlotte   
2415  Sports Direct   2021-09-02  Southeast  North Carolina  Charlotte   
2433  Sports Direct   2021-12-02  Southeast  North Carolina  Charlotte   
2475         Amazon   2021-07-09    Midwest            Ohio   Columbus   

                      Product  Price per Unit  Units Sold Sales Method  
0       Men's Street Footwear            50.0        1200     In-store  
1     Men's Athletic Footwear            50.0        1000     In-store  
2     Women's Street Footwear            40.0        1000     In-store  
4               Men's Apparel            60.0         900     In-store  
5             Women's Apparel            50.0        1000     In-store  
...                       ...             ...         ...          ...  
2403    Men's Street Footwear            65.0        1050       Online  
2409    Men's Street Footwear            65.0        1025       Online  
2415    Men's Street Footwear            55.0         925       Online  
2433    Men's Street Footwear            70.0         975       Online  
2475    Men's Street Footwear            65.0         900       Online  

[148 rows x 9 columns]

Show all records where Region is "Northeast" and State is "New York".

In [34]:
df.loc[(df['Region'] == 'Northeast') & (df['State'] == 'New York')]

Retailer Invoice Date     Region     State      City  \
0       Foot Locker   2020-01-01  Northeast  New York  New York   
1       Foot Locker   2020-01-02  Northeast  New York  New York   
2       Foot Locker   2020-01-03  Northeast  New York  New York   
3       Foot Locker   2020-01-04  Northeast  New York  New York   
4       Foot Locker   2020-01-05  Northeast  New York  New York   
...             ...          ...        ...       ...       ...   
7843        Walmart   2020-07-18  Northeast  New York  New York   
7844  Sports Direct   2020-07-19  Northeast  New York  New York   
7845  Sports Direct   2020-07-20  Northeast  New York  New York   
7846  Sports Direct   2020-07-21  Northeast  New York  New York   
7847  Sports Direct   2020-07-22  Northeast  New York  New York   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000     In-store  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
...                         ...             ...         ...          ...  
7843            Women's Apparel            48.0         340       Outlet  
7844      Men's Street Footwear            20.0         270       Outlet  
7845    Men's Athletic Footwear            26.0         270       Outlet  
7846    Women's Street Footwear            27.0         238       Outlet  
7847  Women's Athletic Footwear            27.0         210       Outlet  

[360 rows x 9 columns]

Multiple Conditions

Display rows where Units Sold > 1000 and Price per Unit > $45.00.

In [36]:
df.loc[(df['Units Sold'] > 1000) & (df['Price per Unit']> 45.00)]

Retailer Invoice Date     Region           State           City  \
0       Foot Locker   2020-01-01  Northeast        New York       New York   
6       Foot Locker   2020-01-07  Northeast        New York       New York   
12      Foot Locker   2020-01-25  Northeast        New York       New York   
18      Foot Locker   2020-01-31  Northeast        New York       New York   
24      Foot Locker   2020-02-06  Northeast        New York       New York   
30      Foot Locker   2020-03-04  Northeast        New York       New York   
35      Foot Locker   2020-03-09  Northeast        New York       New York   
36      Foot Locker   2020-03-10  Northeast        New York       New York   
37      Foot Locker   2020-03-11  Northeast        New York       New York   
41      Foot Locker   2020-03-15  Northeast        New York       New York   
42      Foot Locker   2020-03-16  Northeast        New York       New York   
43      Foot Locker   2020-03-17  Northeast        New York       New York   
47          Walmart   2020-04-18  Northeast        New York       New York   
48          Walmart   2020-04-19  Northeast        New York       New York   
56          Walmart   2020-04-27  Northeast        New York       New York   
62          Walmart   2020-05-03  Northeast        New York       New York   
176       West Gear   2021-01-12       West      California  San Francisco   
740       West Gear   2020-04-24  Southeast         Florida          Miami   
746       West Gear   2020-04-24  Southeast         Florida          Miami   
752       West Gear   2020-09-11  Southeast         Florida          Miami   
758       West Gear   2020-09-17  Southeast         Florida          Miami   
764     Foot Locker   2020-09-23  Southeast         Florida          Miami   
782   Sports Direct   2020-05-24  Southeast         Florida          Miami   
2319    Foot Locker   2021-05-05  Southeast  South Carolina     Charleston   
2325    Foot Locker   2021-06-07  Southeast  South Carolina     Charleston   
2331    Foot Locker   2021-07-05  Southeast  South Carolina     Charleston   
2337    Foot Locker   2021-08-06  Southeast  South Carolina     Charleston   
2343    Foot Locker   2021-09-05  Southeast  South Carolina     Charleston   
2361    Foot Locker   2021-12-05  Southeast  South Carolina     Charleston   
2403  Sports Direct   2021-07-02  Southeast  North Carolina      Charlotte   
2409  Sports Direct   2021-08-03  Southeast  North Carolina      Charlotte   

                      Product  Price per Unit  Units Sold Sales Method  
0       Men's Street Footwear            50.0        1200     In-store  
6       Men's Street Footwear            50.0        1250     In-store  
12      Men's Street Footwear            50.0        1220       Outlet  
18      Men's Street Footwear            50.0        1200       Outlet  
24      Men's Street Footwear            60.0        1220       Outlet  
30      Men's Street Footwear            60.0        1250       Outlet  
35            Women's Apparel            65.0        1050       Outlet  
36      Men's Street Footwear            60.0        1275       Outlet  
37    Men's Athletic Footwear            55.0        1025       Outlet  
41            Women's Apparel            65.0        1100       Outlet  
42      Men's Street Footwear            60.0        1250       Outlet  
43    Men's Athletic Footwear            55.0        1025       Outlet  
47            Women's Apparel            65.0        1075       Outlet  
48      Men's Street Footwear            60.0        1200       Outlet  
56      Men's Street Footwear            65.0        1150       Outlet  
62      Men's Street Footwear            65.0        1200       Outlet  
176     Men's Street Footwear            60.0        1025       Outlet  
740     Men's Street Footwear            55.0        1070     In-store  
746     Men's Street Footwear            60.0        1075     In-store  
752     Men's Street Footwear            65.0        1

Show rows where Units Sold < 1000 or Price per Unit < $45.00.

In [37]:
df.loc[(df['Units Sold'] < 1000) | (df['Price per Unit'] < 45.00)]

Retailer Invoice Date     Region          State        City  \
2     Foot Locker   2020-01-03  Northeast       New York    New York   
3     Foot Locker   2020-01-04  Northeast       New York    New York   
4     Foot Locker   2020-01-05  Northeast       New York    New York   
7     Foot Locker   2020-01-08  Northeast       New York    New York   
8     Foot Locker   2020-01-21  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9643  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9644  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9645  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9646  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9647  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
7       Men's Athletic Footwear            50.0         900       Outlet  
8       Women's Street Footwear            40.0         950       Outlet  
...                         ...             ...         ...          ...  
9643              Men's Apparel            50.0          64       Outlet  
9644            Women's Apparel            41.0         105       Outlet  
9645      Men's Street Footwear            41.0         184       Outlet  
9646    Men's Athletic Footwear            42.0          70       Outlet  
9647    Women's Street Footwear            29.0          83       Outlet  

[9601 rows x 9 columns]


Filter rows where Units Sold > 800 and Units Sold < 1200.


In [38]:
df.loc[df['Units Sold'].between(800,1200)]

Retailer Invoice Date     Region        State      City  \
0     Foot Locker   2020-01-01  Northeast     New York  New York   
1     Foot Locker   2020-01-02  Northeast     New York  New York   
2     Foot Locker   2020-01-03  Northeast     New York  New York   
3     Foot Locker   2020-01-04  Northeast     New York  New York   
4     Foot Locker   2020-01-05  Northeast     New York  New York   
...           ...          ...        ...          ...       ...   
2475       Amazon   2021-07-09    Midwest         Ohio  Columbus   
2481       Amazon   2021-08-10    Midwest         Ohio  Columbus   
2505       Amazon   2021-12-09    Midwest         Ohio  Columbus   
2619  Foot Locker   2021-07-16      South  Mississippi   Jackson   
2625      Walmart   2021-08-17      South  Mississippi   Jackson   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000     In-store  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
...                         ...             ...         ...          ...  
2475      Men's Street Footwear            65.0         900       Online  
2481      Men's Street Footwear            65.0         875       Online  
2505      Men's Street Footwear            75.0         825       Online  
2619      Men's Street Footwear            60.0         850       Online  
2625      Men's Street Footwear            60.0         825       Online  

[312 rows x 9 columns]

Select rows where Price per Unit equals $50.00 and Sales Method is "In-store".

In [39]:
df.loc[(df['Price per Unit'] == 50.00) & (df['Sales Method'] == 'In-store')]

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
1     Foot Locker   2020-01-02  Northeast       New York    New York   
5     Foot Locker   2020-01-06  Northeast       New York    New York   
6     Foot Locker   2020-01-07  Northeast       New York    New York   
645     West Gear   2020-05-27       West       Colorado      Denver   
...           ...          ...        ...            ...         ...   
3820       Amazon   2021-03-17  Northeast  New Hampshire  Manchester   
3824       Amazon   2021-03-17  Northeast  New Hampshire  Manchester   
3825       Amazon   2021-04-18  Northeast  New Hampshire  Manchester   
3826       Amazon   2021-04-18  Northeast  New Hampshire  Manchester   
3830       Amazon   2021-04-18  Northeast  New Hampshire  Manchester   

                      Product  Price per Unit  Units Sold Sales Method  
0       Men's Street Footwear            50.0        1200     In-store  
1     Men's Athletic Footwear            50.0        1000     In-store  
5             Women's Apparel            50.0        1000     In-store  
6       Men's Street Footwear            50.0        1250     In-store  
645   Men's Athletic Footwear            50.0         450     In-store  
...                       ...             ...         ...          ...  
3820  Men's Athletic Footwear            50.0         275     In-store  
3824          Women's Apparel            50.0         300     In-store  
3825    Men's Street Footwear            50.0         550     In-store  
3826  Men's Athletic Footwear            50.0         250     In-store  
3830          Women's Apparel            50.0         325     In-store  

[172 rows x 9 columns]

Show records where Units Sold is either 850 or 900.

In [49]:
df.loc[(df['Units Sold'].isin([850,900]))]

Retailer Invoice Date     Region           State         City  \
3     Foot Locker   2020-01-04  Northeast        New York     New York   
4     Foot Locker   2020-01-05  Northeast        New York     New York   
7     Foot Locker   2020-01-08  Northeast        New York     New York   
10    Foot Locker   2020-01-23  Northeast        New York     New York   
16    Foot Locker   2020-01-29  Northeast        New York     New York   
...           ...          ...        ...             ...          ...   
1977    West Gear   2021-08-17      South       Louisiana  New Orleans   
2332  Foot Locker   2021-07-05  Southeast  South Carolina   Charleston   
2338  Foot Locker   2021-08-06  Southeast  South Carolina   Charleston   
2475       Amazon   2021-07-09    Midwest            Ohio     Columbus   
2619  Foot Locker   2021-07-16      South     Mississippi      Jackson   

                        Product  Price per Unit  Units Sold Sales Method  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
7       Men's Athletic Footwear            50.0         900       Outlet  
10                Men's Apparel            60.0         900       Outlet  
16                Men's Apparel            60.0         850       Outlet  
...                         ...             ...         ...          ...  
1977      Men's Street Footwear            95.0         850       Online  
2332    Men's Athletic Footwear            60.0         900       Online  
2338    Men's Athletic Footwear            60.0         900       Online  
2475      Men's Street Footwear            65.0         900       Online  
2619      Men's Street Footwear            60.0         850       Online  

[70 rows x 9 columns]

Get rows where Units Sold is not in [850, 900, 1250].


In [53]:
df.loc[~(df['Units Sold'].isin([850,900,950]))]

Retailer Invoice Date     Region           State        City  \
3       Foot Locker   2020-01-04  Northeast        New York    New York   
4       Foot Locker   2020-01-05  Northeast        New York    New York   
7       Foot Locker   2020-01-08  Northeast        New York    New York   
8       Foot Locker   2020-01-21  Northeast        New York    New York   
10      Foot Locker   2020-01-23  Northeast        New York    New York   
...             ...          ...        ...             ...         ...   
2332    Foot Locker   2021-07-05  Southeast  South Carolina  Charleston   
2338    Foot Locker   2021-08-06  Southeast  South Carolina  Charleston   
2397  Sports Direct   2021-06-04  Southeast  North Carolina   Charlotte   
2475         Amazon   2021-07-09    Midwest            Ohio    Columbus   
2619    Foot Locker   2021-07-16      South     Mississippi     Jackson   

                        Product  Price per Unit  Units Sold Sales Method  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
7       Men's Athletic Footwear            50.0         900       Outlet  
8       Women's Street Footwear            40.0         950       Outlet  
10                Men's Apparel            60.0         900       Outlet  
...                         ...             ...         ...          ...  
2332    Men's Athletic Footwear            60.0         900       Online  
2338    Men's Athletic Footwear            60.0         900       Online  
2397      Men's Street Footwear            50.0         950       Online  
2475      Men's Street Footwear            65.0         900       Online  
2619      Men's Street Footwear            60.0         850       Online  

[88 rows x 9 columns]

Select all rows where Product is in a list of specific product types (e.g. ["Men's Apparel", "Women's Apparel"]).


In [54]:
df.loc[df['Product'].isin(['Men\'s Apparel', 'Women\'s Apparel'])]

Retailer Invoice Date     Region          State        City  \
4     Foot Locker   2020-01-05  Northeast       New York    New York   
5     Foot Locker   2020-01-06  Northeast       New York    New York   
10    Foot Locker   2020-01-23  Northeast       New York    New York   
11    Foot Locker   2020-01-24  Northeast       New York    New York   
16    Foot Locker   2020-01-29  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9632  Foot Locker   2021-11-18  Northeast  New Hampshire  Manchester   
9637  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9638  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9643  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9644  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   

              Product  Price per Unit  Units Sold Sales Method  
4       Men's Apparel            60.0         900     In-store  
5     Women's Apparel            50.0        1000     In-store  
10      Men's Apparel            60.0         900       Outlet  
11    Women's Apparel            50.0        1000       Outlet  
16      Men's Apparel            60.0         850       Outlet  
...               ...             ...         ...          ...  
9632  Women's Apparel            61.0         120       Outlet  
9637    Men's Apparel            50.0         123       Outlet  
9638  Women's Apparel            61.0         144       Outlet  
9643    Men's Apparel            50.0          64       Outlet  
9644  Women's Apparel            41.0         105       Outlet  

[3214 rows x 9 columns]

Display all rows where Units Sold <= 1000 and Price per Unit >= $45.00

In [55]:
df.loc[(df['Units Sold'] <= 1000) & (df['Price per Unit'] >= 45.00 )]

Retailer Invoice Date     Region          State        City  \
1     Foot Locker   2020-01-02  Northeast       New York    New York   
3     Foot Locker   2020-01-04  Northeast       New York    New York   
4     Foot Locker   2020-01-05  Northeast       New York    New York   
5     Foot Locker   2020-01-06  Northeast       New York    New York   
7     Foot Locker   2020-01-08  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9635  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9636  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9637  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9638  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9643  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
1       Men's Athletic Footwear            50.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
5               Women's Apparel            50.0        1000     In-store  
7       Men's Athletic Footwear            50.0         900       Outlet  
...                         ...             ...         ...          ...  
9635    Women's Street Footwear            47.0         128       Outlet  
9636  Women's Athletic Footwear            49.0         116       Outlet  
9637              Men's Apparel            50.0         123       Outlet  
9638            Women's Apparel            61.0         144       Outlet  
9643              Men's Apparel            50.0          64       Outlet  

[4939 rows x 9 columns]

Filter all rows where both City and State are "New York"

In [57]:
df.loc[(df['City']== 'New York') & (df['State'] == 'New York') ]

Retailer Invoice Date     Region     State      City  \
0       Foot Locker   2020-01-01  Northeast  New York  New York   
1       Foot Locker   2020-01-02  Northeast  New York  New York   
2       Foot Locker   2020-01-03  Northeast  New York  New York   
3       Foot Locker   2020-01-04  Northeast  New York  New York   
4       Foot Locker   2020-01-05  Northeast  New York  New York   
...             ...          ...        ...       ...       ...   
7843        Walmart   2020-07-18  Northeast  New York  New York   
7844  Sports Direct   2020-07-19  Northeast  New York  New York   
7845  Sports Direct   2020-07-20  Northeast  New York  New York   
7846  Sports Direct   2020-07-21  Northeast  New York  New York   
7847  Sports Direct   2020-07-22  Northeast  New York  New York   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000     In-store  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
...                         ...             ...         ...          ...  
7843            Women's Apparel            48.0         340       Outlet  
7844      Men's Street Footwear            20.0         270       Outlet  
7845    Men's Athletic Footwear            26.0         270       Outlet  
7846    Women's Street Footwear            27.0         238       Outlet  
7847  Women's Athletic Footwear            27.0         210       Outlet  

[216 rows x 9 columns]

Show rows where Price per Unit is $45.00 or $50.00.

In [64]:
df.loc[df['Price per Unit'].isin([45.00,50.00])]

Retailer Invoice Date     Region          State        City  \
3640    Foot Locker   2021-09-06  Northeast   Rhode Island  Providence   
3689  Sports Direct   2021-05-13  Northeast  Massachusetts      Boston   
3690  Sports Direct   2021-05-13  Northeast  Massachusetts      Boston   
3695  Sports Direct   2021-06-15  Northeast  Massachusetts      Boston   
3696  Sports Direct   2021-06-15  Northeast  Massachusetts      Boston   
...             ...          ...        ...            ...         ...   
9332  Sports Direct   2021-09-03  Northeast    Connecticut    Hartford   
9345    Foot Locker   2021-12-03  Northeast    Connecticut    Hartford   
9531         Amazon   2021-07-10  Northeast        Vermont  Burlington   
9548         Amazon   2021-09-10  Northeast        Vermont  Burlington   
9613         Amazon   2021-08-18  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
3640    Men's Athletic Footwear            45.0         225     In-store  
3689    Women's Street Footwear            45.0         225     In-store  
3690  Women's Athletic Footwear            45.0         175     In-store  
3695    Women's Street Footwear            45.0         250     In-store  
3696  Women's Athletic Footwear            45.0         225     In-store  
...                         ...             ...         ...          ...  
9332            Women's Apparel            45.0          83       Outlet  
9345      Men's Street Footwear            45.0         173       Outlet  
9531      Men's Street Footwear            45.0         209       Outlet  
9548            Women's Apparel            45.0          93       Outlet  
9613              Men's Apparel            45.0          80       Outlet  

[100 rows x 9 columns]

Using .isin() and .between()

Filter rows where Region is in ["Northeast", "Southwest"].


In [65]:
df.loc[df['Region'].isin(['Northeast','Southwest'])]

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
1     Foot Locker   2020-01-02  Northeast       New York    New York   
2     Foot Locker   2020-01-03  Northeast       New York    New York   
3     Foot Locker   2020-01-04  Northeast       New York    New York   
4     Foot Locker   2020-01-05  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9643  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9644  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9645  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9646  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9647  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000     In-store  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
...                         ...             ...         ...          ...  
9643              Men's Apparel            50.0          64       Outlet  
9644            Women's Apparel            41.0         105       Outlet  
9645      Men's Street Footwear            41.0         184       Outlet  
9646    Men's Athletic Footwear            42.0          70       Outlet  
9647    Women's Street Footwear            29.0          83       Outlet  

[2376 rows x 9 columns]

Display all rows where Units Sold is between 1000 and 1200 (inclusive).

In [66]:
df.loc[df['Units Sold'].between(1000,1200)]

Retailer Invoice Date     Region           State           City  \
0       Foot Locker   2020-01-01  Northeast        New York       New York   
1       Foot Locker   2020-01-02  Northeast        New York       New York   
2       Foot Locker   2020-01-03  Northeast        New York       New York   
5       Foot Locker   2020-01-06  Northeast        New York       New York   
11      Foot Locker   2020-01-24  Northeast        New York       New York   
18      Foot Locker   2020-01-31  Northeast        New York       New York   
29      Foot Locker   2020-03-03  Northeast        New York       New York   
31      Foot Locker   2020-03-05  Northeast        New York       New York   
35      Foot Locker   2020-03-09  Northeast        New York       New York   
37      Foot Locker   2020-03-11  Northeast        New York       New York   
41      Foot Locker   2020-03-15  Northeast        New York       New York   
43      Foot Locker   2020-03-17  Northeast        New York       New York   
47          Walmart   2020-04-18  Northeast        New York       New York   
48          Walmart   2020-04-19  Northeast        New York       New York   
49          Walmart   2020-04-20  Northeast        New York       New York   
53          Walmart   2020-04-24  Northeast        New York       New York   
55          Walmart   2020-04-26  Northeast        New York       New York   
56          Walmart   2020-04-27  Northeast        New York       New York   
62          Walmart   2020-05-03  Northeast        New York       New York   
63          Walmart   2020-05-04  Northeast        New York       New York   
67          Walmart   2020-07-18  Northeast        New York       New York   
103         Walmart   2020-08-23      South           Texas        Houston   
106         Walmart   2020-08-26      South           Texas        Houston   
112         Walmart   2020-09-01      South           Texas        Houston   
176       West Gear   2021-01-12       West      California  San Francisco   
716     Foot Locker   2020-08-06       West      Washington        Seattle   
722     Foot Locker   2020-08-12  Southeast         Florida          Miami   
728     Foot Locker   2020-08-18  Southeast         Florida          Miami   
734     Foot Locker   2020-04-24  Southeast         Florida          Miami   
740       West Gear   2020-04-24  Southeast         Florida          Miami   
746       West Gear   2020-04-24  Southeast         Florida          Miami   
752       West Gear   2020-09-11  Southeast         Florida          Miami   
758       West Gear   2020-09-17  Southeast         Florida          Miami   
764     Foot Locker   2020-09-23  Southeast         Florida          Miami   
770   Sports Direct   2020-09-29  Southeast         Florida          Miami   
782   Sports Direct   2020-05-24  Southeast         Florida          Miami   
2295    Foot Locker   2021-01-09  Southeast         Georgia        Atlanta   
2301    Foot Locker   2021-02-07  Southeast         Georgia        Atlanta   
2307    Foot Locker   2021-03-05  Southeast  South Carolina     Charleston   
2319    Foot Locker   2021-05-05  Southeast  South Carolina     Charleston   
2325    Foot Locker   2021-06-07  Southeast  South Carolina     Charleston   
2331    Foot Locker   2021-07-05  Southeast  South Carolina     Charleston   
2337    Foot Locker   2021-08-06  Southeast  South Carolina     Charleston   
2343    Foot Locker   2021-09-05  Southeast  South Carolina     Charleston   
2361    Foot Locker   2021-12-05  Southeast  South Carolina     Charleston   
2403  Sports Direct   2021-07-02  Southeast  North Carolina      Charlotte   
2409  Sports Direct   2021-08-03  Southeast  North Carolina      Charlotte   

                      Product  Price per Unit  Units Sold Sales Method  
0       Men's Street Footwear            50.0        1200     In-store  
1     Men's Athletic Footwear            50.0        1000     In-store  
2     Women's Street Footwear            40.0  

Select all rows where Price per Unit is between $45.00 and $60.00.

In [67]:
df.loc[df['Price per Unit'].between(45.00,60.00)]

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
1     Foot Locker   2020-01-02  Northeast       New York    New York   
3     Foot Locker   2020-01-04  Northeast       New York    New York   
4     Foot Locker   2020-01-05  Northeast       New York    New York   
5     Foot Locker   2020-01-06  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9634  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9635  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9636  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9637  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9643  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
5               Women's Apparel            50.0        1000     In-store  
...                         ...             ...         ...          ...  
9634    Men's Athletic Footwear            49.0         128       Outlet  
9635    Women's Street Footwear            47.0         128       Outlet  
9636  Women's Athletic Footwear            49.0         116       Outlet  
9637              Men's Apparel            50.0         123       Outlet  
9643              Men's Apparel            50.0          64       Outlet  

[3614 rows x 9 columns]


Get rows where Sales Method is in ["In-store", "Online"].

In [68]:
df.loc[df['Sales Method'].isin(['In-store','Online'])]

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
1     Foot Locker   2020-01-02  Northeast       New York    New York   
2     Foot Locker   2020-01-03  Northeast       New York    New York   
3     Foot Locker   2020-01-04  Northeast       New York    New York   
4     Foot Locker   2020-01-05  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
7771  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
7772  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
7773  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
7774  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
7775  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000     In-store  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
...                         ...             ...         ...          ...  
7771              Men's Apparel            60.0          54       Online  
7772            Women's Apparel            54.0          78       Online  
7773      Men's Street Footwear            52.0         173       Online  
7774    Men's Athletic Footwear            53.0          59       Online  
7775    Women's Street Footwear            43.0          83       Online  

[6629 rows x 9 columns]

Exclude all rows where Region is in ["Northwest", "Midwest"] using ~.

In [71]:
df.loc[~(df['Region'].isin(['Northwest','Midwest']))]

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
1     Foot Locker   2020-01-02  Northeast       New York    New York   
2     Foot Locker   2020-01-03  Northeast       New York    New York   
3     Foot Locker   2020-01-04  Northeast       New York    New York   
4     Foot Locker   2020-01-05  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9643  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9644  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9645  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9646  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9647  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000     In-store  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
...                         ...             ...         ...          ...  
9643              Men's Apparel            50.0          64       Outlet  
9644            Women's Apparel            41.0         105       Outlet  
9645      Men's Street Footwear            41.0         184       Outlet  
9646    Men's Athletic Footwear            42.0          70       Outlet  
9647    Women's Street Footwear            29.0          83       Outlet  

[7776 rows x 9 columns]

Show records where Units Sold is not between 900 and 1100.

In [75]:
df.loc[~(df['Units Sold'].between(900,1100))]

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
3     Foot Locker   2020-01-04  Northeast       New York    New York   
6     Foot Locker   2020-01-07  Northeast       New York    New York   
9     Foot Locker   2020-01-22  Northeast       New York    New York   
12    Foot Locker   2020-01-25  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9643  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9644  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9645  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9646  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9647  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
6         Men's Street Footwear            50.0        1250     In-store  
9     Women's Athletic Footwear            45.0         825       Outlet  
12        Men's Street Footwear            50.0        1220       Outlet  
...                         ...             ...         ...          ...  
9643              Men's Apparel            50.0          64       Outlet  
9644            Women's Apparel            41.0         105       Outlet  
9645      Men's Street Footwear            41.0         184       Outlet  
9646    Men's Athletic Footwear            42.0          70       Outlet  
9647    Women's Street Footwear            29.0          83       Outlet  

[9509 rows x 9 columns]

Get rows where both Region and Sales Method are in given lists.

In [76]:
df.loc[(df['Region'].isin(['Northeast', 'Southwest'])) &
       (df['Sales Method'].isin(['In-store', 'Online']))]

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
1     Foot Locker   2020-01-02  Northeast       New York    New York   
2     Foot Locker   2020-01-03  Northeast       New York    New York   
3     Foot Locker   2020-01-04  Northeast       New York    New York   
4     Foot Locker   2020-01-05  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
7771  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
7772  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
7773  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
7774  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
7775  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000     In-store  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
...                         ...             ...         ...          ...  
7771              Men's Apparel            60.0          54       Online  
7772            Women's Apparel            54.0          78       Online  
7773      Men's Street Footwear            52.0         173       Online  
7774    Men's Athletic Footwear            53.0          59       Online  
7775    Women's Street Footwear            43.0          83       Online  

[1619 rows x 9 columns]

Select rows where Price per Unit is between $40.00 and $50.00 and Units Sold > 900.

In [78]:
df.loc[(df['Price per Unit'].between(40.00,50.00)) & (df['Units Sold'] > 900)]

Retailer Invoice Date     Region           State         City  \
0       Foot Locker   2020-01-01  Northeast        New York     New York   
1       Foot Locker   2020-01-02  Northeast        New York     New York   
2       Foot Locker   2020-01-03  Northeast        New York     New York   
5       Foot Locker   2020-01-06  Northeast        New York     New York   
6       Foot Locker   2020-01-07  Northeast        New York     New York   
8       Foot Locker   2020-01-21  Northeast        New York     New York   
11      Foot Locker   2020-01-24  Northeast        New York     New York   
12      Foot Locker   2020-01-25  Northeast        New York     New York   
13      Foot Locker   2020-01-26  Northeast        New York     New York   
14      Foot Locker   2020-01-27  Northeast        New York     New York   
17      Foot Locker   2020-01-30  Northeast        New York     New York   
18      Foot Locker   2020-01-31  Northeast        New York     New York   
23      Foot Locker   2020-02-05  Northeast        New York     New York   
32      Foot Locker   2020-03-06  Northeast        New York     New York   
38      Foot Locker   2020-03-12  Northeast        New York     New York   
44      Foot Locker   2020-03-18  Northeast        New York     New York   
45      Foot Locker   2020-03-31  Northeast        New York     New York   
50          Walmart   2020-04-21  Northeast        New York     New York   
93          Walmart   2020-08-13      South           Texas      Houston   
97          Walmart   2020-08-17      South           Texas      Houston   
98          Walmart   2020-08-18      South           Texas      Houston   
99          Walmart   2020-08-19      South           Texas      Houston   
103         Walmart   2020-08-23      South           Texas      Houston   
104         Walmart   2020-08-24      South           Texas      Houston   
105         Walmart   2020-08-25      South           Texas      Houston   
106         Walmart   2020-08-26      South           Texas      Houston   
109         Walmart   2020-08-29      South           Texas      Houston   
110         Walmart   2020-08-30      South           Texas      Houston   
111         Walmart   2020-08-31      South           Texas      Houston   
112         Walmart   2020-09-01      South           Texas      Houston   
134         Walmart   2020-10-26      South           Texas      Houston   
135         Walmart   2020-10-27      South           Texas      Houston   
248          Kohl's   2021-04-25       West      California  Los Angeles   
394   Sports Direct   2021-09-18      South           Texas       Dallas   
400   Sports Direct   2021-09-24      South           Texas       Dallas   
716     Foot Locker   2020-08-06       West      Washington      Seattle   
722     Foot Locker   2020-08-12  Southeast         Florida        Miami   
728     Foot Locker   2020-08-18  Southeast         Florida        Miami   
734     Foot Locker   2020-04-24  Southeast         Florida        Miami   
970   Sports Direct   2021-04-17      South       Tennessee    Knoxville   
976   Sports Direct   2021-04-23      South       Tennessee    Knoxville   
1114  Sports Direct   2021-09-08      South         Alabama   Birmingham   
2045      West Gear   2021-07-06       West           Idaho        Boise   
2051    Foot Locker   2021-08-08       West           Idaho        Boise   
2295    Foot Locker   2021-01-09  Southeast         Georgia      Atlanta   
2301    Foot Locker   2021-02-07  Southeast         Georgia      Atlanta   
2319    Foot Locker   2021-05-05  Southeast  South Carolina   Charleston   
2391  Sports Direct   2021-05-02  Southeast  North Carolina    Charlotte   
2397  Sports Direct   2021-06-04  Southeast  North Carolina    Charlotte   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000 

Display rows where Units Sold is in [850, 1000, 1200, 1250].

In [79]:
df.loc[df['Units Sold'].isin([850,1000,1200,1250])]

Retailer Invoice Date     Region        State           City  \
0       Foot Locker   2020-01-01  Northeast     New York       New York   
1       Foot Locker   2020-01-02  Northeast     New York       New York   
2       Foot Locker   2020-01-03  Northeast     New York       New York   
3       Foot Locker   2020-01-04  Northeast     New York       New York   
5       Foot Locker   2020-01-06  Northeast     New York       New York   
6       Foot Locker   2020-01-07  Northeast     New York       New York   
11      Foot Locker   2020-01-24  Northeast     New York       New York   
16      Foot Locker   2020-01-29  Northeast     New York       New York   
18      Foot Locker   2020-01-31  Northeast     New York       New York   
27      Foot Locker   2020-02-09  Northeast     New York       New York   
29      Foot Locker   2020-03-03  Northeast     New York       New York   
30      Foot Locker   2020-03-04  Northeast     New York       New York   
31      Foot Locker   2020-03-05  Northeast     New York       New York   
42      Foot Locker   2020-03-16  Northeast     New York       New York   
48          Walmart   2020-04-19  Northeast     New York       New York   
49          Walmart   2020-04-20  Northeast     New York       New York   
53          Walmart   2020-04-24  Northeast     New York       New York   
55          Walmart   2020-04-26  Northeast     New York       New York   
62          Walmart   2020-05-03  Northeast     New York       New York   
63          Walmart   2020-05-04  Northeast     New York       New York   
67          Walmart   2020-07-18  Northeast     New York       New York   
74    Sports Direct   2020-07-25      South        Texas        Houston   
75    Sports Direct   2020-07-26      South        Texas        Houston   
103         Walmart   2020-08-23      South        Texas        Houston   
116         Walmart   2020-09-05      South        Texas        Houston   
117         Walmart   2020-09-06      South        Texas        Houston   
121         Walmart   2020-09-10      South        Texas        Houston   
133         Walmart   2020-10-25      South        Texas        Houston   
136         Walmart   2020-10-28      South        Texas        Houston   
152       West Gear   2020-11-13       West   California  San Francisco   
255          Kohl's   2021-05-02       West   California    Los Angeles   
260          Kohl's   2021-05-07       West   California    Los Angeles   
261          Kohl's   2021-05-08       West   California    Los Angeles   
397   Sports Direct   2021-09-21      South        Texas         Dallas   
717     Foot Locker   2020-08-07       West   Washington        Seattle   
718     Foot Locker   2020-08-08       West   Washington        Seattle   
721     Foot Locker   2020-08-11  Southeast      Florida          Miami   
727     Foot Locker   2020-08-17  Southeast      Florida          Miami   
765     Foot Locker   2020-09-24  Southeast      Florida          Miami   
770   Sports Direct   2020-09-29  Southeast      Florida          Miami   
781   Sports Direct   2020-10-10  Southeast      Florida          Miami   
1401        Walmart   2021-08-17  Southeast      Florida        Orlando   
1431      West Gear   2021-01-12  Southeast      Florida        Orlando   
1479      West Gear   2021-09-08  Northeast     New York         Albany   
1509         Kohl's   2021-02-12  Northeast     New York         Albany   
1533         Kohl's   2021-06-12       West      Wyoming       Cheyenne   
1545         Kohl's   2021-08-11       West      Wyoming       Cheyenne   
1611    Foot Locker   2021-07-23  Southeast     Virginia       Richmond   
1713  Sports Direct   2021-12-15    Midwest     Michigan        Detroit   
1899      West Gear   2021-07-23       West       Oregon       Portland   
1977      West Gear   2021-08-17      South    Louisiana    New Orleans   
2619    Foot Locker   2021-07-16      South  Mississippi        Jackson   

                        Product  Pr

Filter out rows where Units Sold is in [850, 900].

In [81]:
df.loc[df['Units Sold'].isin([850,900])]

Retailer Invoice Date     Region           State         City  \
3     Foot Locker   2020-01-04  Northeast        New York     New York   
4     Foot Locker   2020-01-05  Northeast        New York     New York   
7     Foot Locker   2020-01-08  Northeast        New York     New York   
10    Foot Locker   2020-01-23  Northeast        New York     New York   
16    Foot Locker   2020-01-29  Northeast        New York     New York   
...           ...          ...        ...             ...          ...   
1977    West Gear   2021-08-17      South       Louisiana  New Orleans   
2332  Foot Locker   2021-07-05  Southeast  South Carolina   Charleston   
2338  Foot Locker   2021-08-06  Southeast  South Carolina   Charleston   
2475       Amazon   2021-07-09    Midwest            Ohio     Columbus   
2619  Foot Locker   2021-07-16      South     Mississippi      Jackson   

                        Product  Price per Unit  Units Sold Sales Method  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
7       Men's Athletic Footwear            50.0         900       Outlet  
10                Men's Apparel            60.0         900       Outlet  
16                Men's Apparel            60.0         850       Outlet  
...                         ...             ...         ...          ...  
1977      Men's Street Footwear            95.0         850       Online  
2332    Men's Athletic Footwear            60.0         900       Online  
2338    Men's Athletic Footwear            60.0         900       Online  
2475      Men's Street Footwear            65.0         900       Online  
2619      Men's Street Footwear            60.0         850       Online  

[70 rows x 9 columns]

Using .iloc for positional filtering

Display the first 10 rows using .iloc

In [82]:
df.iloc[:10]

Retailer Invoice Date     Region     State      City  \
0  Foot Locker   2020-01-01  Northeast  New York  New York   
1  Foot Locker   2020-01-02  Northeast  New York  New York   
2  Foot Locker   2020-01-03  Northeast  New York  New York   
3  Foot Locker   2020-01-04  Northeast  New York  New York   
4  Foot Locker   2020-01-05  Northeast  New York  New York   
5  Foot Locker   2020-01-06  Northeast  New York  New York   
6  Foot Locker   2020-01-07  Northeast  New York  New York   
7  Foot Locker   2020-01-08  Northeast  New York  New York   
8  Foot Locker   2020-01-21  Northeast  New York  New York   
9  Foot Locker   2020-01-22  Northeast  New York  New York   

                     Product  Price per Unit  Units Sold Sales Method  
0      Men's Street Footwear            50.0        1200     In-store  
1    Men's Athletic Footwear            50.0        1000     In-store  
2    Women's Street Footwear            40.0        1000     In-store  
3  Women's Athletic Footwear            45.0         850     In-store  
4              Men's Apparel            60.0         900     In-store  
5            Women's Apparel            50.0        1000     In-store  
6      Men's Street Footwear            50.0        1250     In-store  
7    Men's Athletic Footwear            50.0         900       Outlet  
8    Women's Street Footwear            40.0         950       Outlet  
9  Women's Athletic Footwear            45.0         825       Outlet

Show rows from index position 100 to 120.

In [83]:
df.iloc[100:121]

Retailer Invoice Date Region  State     City                    Product  \
100  Walmart   2020-08-20  South  Texas  Houston    Women's Street Footwear   
101  Walmart   2020-08-21  South  Texas  Houston  Women's Athletic Footwear   
102  Walmart   2020-08-22  South  Texas  Houston              Men's Apparel   
103  Walmart   2020-08-23  South  Texas  Houston            Women's Apparel   
104  Walmart   2020-08-24  South  Texas  Houston      Men's Street Footwear   
105  Walmart   2020-08-25  South  Texas  Houston    Men's Athletic Footwear   
106  Walmart   2020-08-26  South  Texas  Houston    Women's Street Footwear   
107  Walmart   2020-08-27  South  Texas  Houston  Women's Athletic Footwear   
108  Walmart   2020-08-28  South  Texas  Houston              Men's Apparel   
109  Walmart   2020-08-29  South  Texas  Houston            Women's Apparel   
110  Walmart   2020-08-30  South  Texas  Houston      Men's Street Footwear   
111  Walmart   2020-08-31  South  Texas  Houston    Men's Athletic Footwear   
112  Walmart   2020-09-01  South  Texas  Houston    Women's Street Footwear   
113  Walmart   2020-09-02  South  Texas  Houston  Women's Athletic Footwear   
114  Walmart   2020-09-03  South  Texas  Houston              Men's Apparel   
115  Walmart   2020-09-04  South  Texas  Houston            Women's Apparel   
116  Walmart   2020-09-05  South  Texas  Houston      Men's Street Footwear   
117  Walmart   2020-09-06  South  Texas  Houston    Men's Athletic Footwear   
118  Walmart   2020-09-07  South  Texas  Houston    Women's Street Footwear   
119  Walmart   2020-09-08  South  Texas  Houston  Women's Athletic Footwear   

     Price per Unit  Units Sold Sales Method  
100            40.0         800       Outlet  
101            40.0         750       Outlet  
102            45.0         650       Outlet  
103            50.0        1000       Outlet  
104            40.0         950       Outlet  
105            45.0         950       Outlet  
106            40.0        1100       Outlet  
107            40.0         700       Outlet  
108            45.0         700       Outlet  
109            50.0         975       Outlet  
110            40.0         925       Outlet  
111            45.0         925       Outlet  
112            40.0        1100       Outlet  
113            40.0         650       Outlet  
114            45.0         650       Outlet  
115            50.0         900       Outlet  
116            45.0         850       Outlet  
117            45.0         850       Outlet  
118            50.0         900       Outlet  
119            50.0         625       Outlet

Display every 5th row using .iloc.

In [84]:
df.iloc[::5]

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
5     Foot Locker   2020-01-06  Northeast       New York    New York   
10    Foot Locker   2020-01-23  Northeast       New York    New York   
15    Foot Locker   2020-01-28  Northeast       New York    New York   
20    Foot Locker   2020-02-02  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9625  Foot Locker   2021-10-19  Northeast  New Hampshire  Manchester   
9630  Foot Locker   2021-11-18  Northeast  New Hampshire  Manchester   
9635  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9640  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9645  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
5               Women's Apparel            50.0        1000     In-store  
10                Men's Apparel            60.0         900       Outlet  
15    Women's Athletic Footwear            45.0         800       Outlet  
20      Women's Street Footwear            40.0         900       Outlet  
...                         ...             ...         ...          ...  
9625              Men's Apparel            50.0          58       Outlet  
9630  Women's Athletic Footwear            43.0         114       Outlet  
9635    Women's Street Footwear            47.0         128       Outlet  
9640    Men's Athletic Footwear            36.0          93       Outlet  
9645      Men's Street Footwear            41.0         184       Outlet  

[1930 rows x 9 columns]

Show the last 10 rows using negative indices.


In [86]:
df.iloc[-10:]

Retailer Invoice Date     Region          State        City  \
9638  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9639  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9640  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9641  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9642  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9643  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9644  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9645  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9646  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9647  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
9638            Women's Apparel            61.0         144       Outlet  
9639      Men's Street Footwear            36.0         165       Outlet  
9640    Men's Athletic Footwear            36.0          93       Outlet  
9641    Women's Street Footwear            35.0          99       Outlet  
9642  Women's Athletic Footwear            33.0          51       Outlet  
9643              Men's Apparel            50.0          64       Outlet  
9644            Women's Apparel            41.0         105       Outlet  
9645      Men's Street Footwear            41.0         184       Outlet  
9646    Men's Athletic Footwear            42.0          70       Outlet  
9647    Women's Street Footwear            29.0          83       Outlet

Display alternate rows from the dataset (even index rows).

In [87]:
df.iloc[::2]

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
2     Foot Locker   2020-01-03  Northeast       New York    New York   
4     Foot Locker   2020-01-05  Northeast       New York    New York   
6     Foot Locker   2020-01-07  Northeast       New York    New York   
8     Foot Locker   2020-01-21  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9638  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9640  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9642  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9644  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9646  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
2       Women's Street Footwear            40.0        1000     In-store  
4                 Men's Apparel            60.0         900     In-store  
6         Men's Street Footwear            50.0        1250     In-store  
8       Women's Street Footwear            40.0         950       Outlet  
...                         ...             ...         ...          ...  
9638            Women's Apparel            61.0         144       Outlet  
9640    Men's Athletic Footwear            36.0          93       Outlet  
9642  Women's Athletic Footwear            33.0          51       Outlet  
9644            Women's Apparel            41.0         105       Outlet  
9646    Men's Athletic Footwear            42.0          70       Outlet  

[4824 rows x 9 columns]

Select rows between position 50 and 60 where Units Sold > 1000.

In [91]:
df.iloc[50:61][df.iloc[50:61]['Units Sold'] > 1000]

Retailer Invoice Date     Region     State      City  \
56  Walmart   2020-04-27  Northeast  New York  New York   

                  Product  Price per Unit  Units Sold Sales Method  
56  Men's Street Footwear            65.0        1150       Outlet


Using .iloc, get the first 3 rows and specific columns (Retailer, Units Sold).

In [95]:
df.iloc[:4][['Retailer','Units Sold']]

Retailer  Units Sold
0  Foot Locker        1200
1  Foot Locker        1000
2  Foot Locker        1000
3  Foot Locker         850

Get rows from index 10 to 20 for columns Product and Units Sold.

In [99]:
df.iloc[10:21][['Product','Units Sold']]

Product  Units Sold
10              Men's Apparel         900
11            Women's Apparel        1000
12      Men's Street Footwear        1220
13    Men's Athletic Footwear         925
14    Women's Street Footwear         950
15  Women's Athletic Footwear         800
16              Men's Apparel         850
17            Women's Apparel         950
18      Men's Street Footwear        1200
19    Men's Athletic Footwear         900
20    Women's Street Footwear         900

Fetch rows using a list of specific index positions (e.g., [0, 2, 5, 7]).

In [101]:
df.iloc[[0,2,5,7]]

Retailer Invoice Date     Region     State      City  \
0  Foot Locker   2020-01-01  Northeast  New York  New York   
2  Foot Locker   2020-01-03  Northeast  New York  New York   
5  Foot Locker   2020-01-06  Northeast  New York  New York   
7  Foot Locker   2020-01-08  Northeast  New York  New York   

                   Product  Price per Unit  Units Sold Sales Method  
0    Men's Street Footwear            50.0        1200     In-store  
2  Women's Street Footwear            40.0        1000     In-store  
5          Women's Apparel            50.0        1000     In-store  
7  Men's Athletic Footwear            50.0         900       Outlet

Select the middle 10% of records using .iloc

In [102]:
middle_start = int(len(df) * 0.45)
middle_end = int(len(df) * 0.55)
df.iloc[middle_start:middle_end]

Retailer Invoice Date     Region         State          City  \
4341  Foot Locker   2021-11-16  Northeast  Pennsylvania  Philadelphia   
4342  Foot Locker   2021-11-17  Northeast  Pennsylvania  Philadelphia   
4343  Foot Locker   2021-11-18  Northeast  Pennsylvania  Philadelphia   
4344  Foot Locker   2021-11-19  Northeast  Pennsylvania  Philadelphia   
4345  Foot Locker   2021-11-20  Northeast  Pennsylvania  Philadelphia   
...           ...          ...        ...           ...           ...   
5301      Walmart   2021-10-17  Southeast       Florida       Orlando   
5302      Walmart   2021-10-17  Southeast       Florida       Orlando   
5303      Walmart   2021-10-17  Southeast       Florida       Orlando   
5304      Walmart   2021-10-17  Southeast       Florida       Orlando   
5305      Walmart   2021-10-17  Southeast       Florida       Orlando   

                        Product  Price per Unit  Units Sold Sales Method  
4341    Men's Athletic Footwear            54.0          53       Online  
4342    Women's Street Footwear            52.0          42       Online  
4343  Women's Athletic Footwear            51.0          29       Online  
4344              Men's Apparel            59.0          31       Online  
4345            Women's Apparel            64.0          63       Online  
...                         ...             ...         ...          ...  
5301      Men's Street Footwear            47.0         100       Online  
5302    Men's Athletic Footwear            59.0         144       Online  
5303    Women's Street Footwear            55.0         112       Online  
5304  Women's Athletic Footwear            51.0         113       Online  
5305              Men's Apparel            59.0          98       Online  

[965 rows x 9 columns]

Use .loc to select rows where Price per Unit > $45.00.

In [103]:
df.loc[df['Price per Unit']>45.00]

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
1     Foot Locker   2020-01-02  Northeast       New York    New York   
4     Foot Locker   2020-01-05  Northeast       New York    New York   
5     Foot Locker   2020-01-06  Northeast       New York    New York   
6     Foot Locker   2020-01-07  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9635  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9636  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9637  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9638  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9643  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000     In-store  
4                 Men's Apparel            60.0         900     In-store  
5               Women's Apparel            50.0        1000     In-store  
6         Men's Street Footwear            50.0        1250     In-store  
...                         ...             ...         ...          ...  
9635    Women's Street Footwear            47.0         128       Outlet  
9636  Women's Athletic Footwear            49.0         116       Outlet  
9637              Men's Apparel            50.0         123       Outlet  
9638            Women's Apparel            61.0         144       Outlet  
9643              Men's Apparel            50.0          64       Outlet  

[4537 rows x 9 columns]

Use .loc to select rows where Units Sold < 1000 and Product is "Men's Street Footwear".



In [104]:
df.loc[(df['Units Sold']<1000) & (df['Product'] == 'Men\'s Street Footwear')]

Retailer Invoice Date     Region          State        City  \
68    Sports Direct   2020-07-19  Northeast       New York    New York   
74    Sports Direct   2020-07-25      South          Texas     Houston   
80    Sports Direct   2020-07-31      South          Texas     Houston   
86    Sports Direct   2020-08-06      South          Texas     Houston   
92          Walmart   2020-08-12      South          Texas     Houston   
...             ...          ...        ...            ...         ...   
9621    Foot Locker   2021-10-19  Northeast  New Hampshire  Manchester   
9627    Foot Locker   2021-11-18  Northeast  New Hampshire  Manchester   
9633    Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9639    Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9645    Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                    Product  Price per Unit  Units Sold Sales Method  
68    Men's Street Footwear            25.0         900       Outlet  
74    Men's Street Footwear            25.0         850       Outlet  
80    Men's Street Footwear            30.0         875       Outlet  
86    Men's Street Footwear            30.0         900       Outlet  
92    Men's Street Footwear            30.0         925       Outlet  
...                     ...             ...         ...          ...  
9621  Men's Street Footwear            52.0         162       Outlet  
9627  Men's Street Footwear            59.0         149       Outlet  
9633  Men's Street Footwear            49.0         200       Outlet  
9639  Men's Street Footwear            36.0         165       Outlet  
9645  Men's Street Footwear            41.0         184       Outlet  

[1576 rows x 9 columns]

Using .loc, filter rows where Sales Method is "In-store" and Region is "Northeast".

In [105]:
df.loc[(df['Sales Method']== 'In-store') & (df['Region'] == 'Northeast')]

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
1     Foot Locker   2020-01-02  Northeast       New York    New York   
2     Foot Locker   2020-01-03  Northeast       New York    New York   
3     Foot Locker   2020-01-04  Northeast       New York    New York   
4     Foot Locker   2020-01-05  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
3839       Amazon   2021-06-19  Northeast  New Hampshire  Manchester   
3840       Amazon   2021-06-19  Northeast  New Hampshire  Manchester   
3841       Amazon   2021-06-19  Northeast  New Hampshire  Manchester   
3842       Amazon   2021-06-19  Northeast  New Hampshire  Manchester   
3843       Amazon   2021-07-17  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000     In-store  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
...                         ...             ...         ...          ...  
3839    Women's Street Footwear            55.0         350     In-store  
3840  Women's Athletic Footwear            55.0         325     In-store  
3841              Men's Apparel            65.0         325     In-store  
3842            Women's Apparel            70.0         475     In-store  
3843      Men's Street Footwear            65.0         700     In-store  

[683 rows x 9 columns]

Using .loc, select rows where Units Sold > 1000 or Product is "Women's Apparel".

In [106]:
df.loc[(df["Units Sold"]>1000) | (df['Product'] == 'Women\'s Apparel')]

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
5     Foot Locker   2020-01-06  Northeast       New York    New York   
6     Foot Locker   2020-01-07  Northeast       New York    New York   
11    Foot Locker   2020-01-24  Northeast       New York    New York   
12    Foot Locker   2020-01-25  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9620       Amazon   2021-09-17  Northeast  New Hampshire  Manchester   
9626  Foot Locker   2021-10-19  Northeast  New Hampshire  Manchester   
9632  Foot Locker   2021-11-18  Northeast  New Hampshire  Manchester   
9638  Foot Locker   2021-12-17  Northeast  New Hampshire  Manchester   
9644  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   

                    Product  Price per Unit  Units Sold Sales Method  
0     Men's Street Footwear            50.0        1200     In-store  
5           Women's Apparel            50.0        1000     In-store  
6     Men's Street Footwear            50.0        1250     In-store  
11          Women's Apparel            50.0        1000       Outlet  
12    Men's Street Footwear            50.0        1220       Outlet  
...                     ...             ...         ...          ...  
9620        Women's Apparel            53.0         104       Outlet  
9626        Women's Apparel            64.0          90       Outlet  
9632        Women's Apparel            61.0         120       Outlet  
9638        Women's Apparel            61.0         144       Outlet  
9644        Women's Apparel            41.0         105       Outlet  

[1645 rows x 9 columns]

With .loc, exclude rows where Price per Unit equals $50.00.


In [107]:
df.loc[~(df['Price per Unit'] == 50.00)]

Retailer Invoice Date     Region          State        City  \
2     Foot Locker   2020-01-03  Northeast       New York    New York   
3     Foot Locker   2020-01-04  Northeast       New York    New York   
4     Foot Locker   2020-01-05  Northeast       New York    New York   
8     Foot Locker   2020-01-21  Northeast       New York    New York   
9     Foot Locker   2020-01-22  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9642  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9644  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9645  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9646  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9647  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
8       Women's Street Footwear            40.0         950       Outlet  
9     Women's Athletic Footwear            45.0         825       Outlet  
...                         ...             ...         ...          ...  
9642  Women's Athletic Footwear            33.0          51       Outlet  
9644            Women's Apparel            41.0         105       Outlet  
9645      Men's Street Footwear            41.0         184       Outlet  
9646    Men's Athletic Footwear            42.0          70       Outlet  
9647    Women's Street Footwear            29.0          83       Outlet  

[9091 rows x 9 columns]

Updating Records using .loc

Update Sales Method to "Online" where Units Sold > 1200. - problem

In [113]:
df.loc[df['Units Sold'] > 1200, 'Sales Method' ] == ' online'
df

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
1     Foot Locker   2020-01-02  Northeast       New York    New York   
2     Foot Locker   2020-01-03  Northeast       New York    New York   
3     Foot Locker   2020-01-04  Northeast       New York    New York   
4     Foot Locker   2020-01-05  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9643  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9644  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9645  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9646  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9647  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000     In-store  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
...                         ...             ...         ...          ...  
9643              Men's Apparel            50.0          64       Outlet  
9644            Women's Apparel            41.0         105       Outlet  
9645      Men's Street Footwear            41.0         184       Outlet  
9646    Men's Athletic Footwear            42.0          70       Outlet  
9647    Women's Street Footwear            29.0          83       Outlet  

[9648 rows x 9 columns]

Change Price per Unit to $55.00 for all "Men's Apparel" products.

In [115]:

df.loc[df['Product'] == 'Men\'s Apparel', 'Price per Unit'] = 55.00
df

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01  Northeast       New York    New York   
1     Foot Locker   2020-01-02  Northeast       New York    New York   
2     Foot Locker   2020-01-03  Northeast       New York    New York   
3     Foot Locker   2020-01-04  Northeast       New York    New York   
4     Foot Locker   2020-01-05  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9643  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9644  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9645  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9646  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9647  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000     In-store  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            60.0         900     In-store  
...                         ...             ...         ...          ...  
9643              Men's Apparel            50.0          64       Outlet  
9644            Women's Apparel            41.0         105       Outlet  
9645      Men's Street Footwear            41.0         184       Outlet  
9646    Men's Athletic Footwear            42.0          70       Outlet  
9647    Women's Street Footwear            29.0          83       Outlet  

[9648 rows x 9 columns]

Set Region to "East" for all rows where State is "New York".

In [117]:
df.loc[df['State'] == 'New York' , 'Region' ] = 'East'
df

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01       East       New York    New York   
1     Foot Locker   2020-01-02       East       New York    New York   
2     Foot Locker   2020-01-03       East       New York    New York   
3     Foot Locker   2020-01-04       East       New York    New York   
4     Foot Locker   2020-01-05       East       New York    New York   
...           ...          ...        ...            ...         ...   
9643  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9644  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9645  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9646  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9647  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            50.0        1200     In-store  
1       Men's Athletic Footwear            50.0        1000     In-store  
2       Women's Street Footwear            40.0        1000     In-store  
3     Women's Athletic Footwear            45.0         850     In-store  
4                 Men's Apparel            55.0         900     In-store  
...                         ...             ...         ...          ...  
9643              Men's Apparel            55.0          64       Outlet  
9644            Women's Apparel            41.0         105       Outlet  
9645      Men's Street Footwear            41.0         184       Outlet  
9646    Men's Athletic Footwear            42.0          70       Outlet  
9647    Women's Street Footwear            29.0          83       Outlet  

[9648 rows x 9 columns]

Increase Units Sold by 10% for all rows where Product contains "Footwear". Problem

Update multiple columns — set Price per Unit = "$60.00" and Sales Method = "Online" where Units Sold > 1000.

In [123]:
df.loc[df["Units Sold"] > 1000, ["Price per Unit", "Sales Method"]] = [60.00, "Online"]
df

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   2020-01-01       East       New York    New York   
1     Foot Locker   2020-01-02       East       New York    New York   
2     Foot Locker   2020-01-03       East       New York    New York   
3     Foot Locker   2020-01-04       East       New York    New York   
4     Foot Locker   2020-01-05       East       New York    New York   
...           ...          ...        ...            ...         ...   
9643  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9644  Foot Locker   2021-01-24  Northeast  New Hampshire  Manchester   
9645  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9646  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   
9647  Foot Locker   2021-02-22  Northeast  New Hampshire  Manchester   

                        Product  Price per Unit  Units Sold Sales Method  
0         Men's Street Footwear            60.0        1320       Online  
1       Men's Athletic Footwear            60.0        1100       Online  
2       Women's Street Footwear            60.0        1100       Online  
3     Women's Athletic Footwear            45.0         935     In-store  
4                 Men's Apparel            55.0         900     In-store  
...                         ...             ...         ...          ...  
9643              Men's Apparel            55.0          64       Outlet  
9644            Women's Apparel            41.0         105       Outlet  
9645      Men's Street Footwear            41.0         202       Outlet  
9646    Men's Athletic Footwear            42.0          77       Outlet  
9647    Women's Street Footwear            29.0          91       Outlet  

[9648 rows x 9 columns]